AM1CODES/Poke-Dex

about.css, about.html, index.css, index.html
I Have Added **3 More Pokemons** To Original File, **Changed UI of Pages**, Added **Back To Top Button** and **Jump Section** Button and Finally I Made It **Responsive Than Before**
=> Added Some Pokemons,Changed UI and Made it Responsive

index.css, index.html
=> Add raichu card

index.html
=> Revert "Added JigglyPuff."

index.html
=> Revert "Ananya"

index.html
=> added a new pokemon

index.html
Made a card and pushed changes.
=> ananya's updates

index.html
=> added jolteon

index.html
Added a card of Mewtwo with description and and my github link and name.
=> Added a card of Mewtwo with description and my name

index.html
=> Added new Pokémon

index.html
=> Added gyarados

README.md
There was a small typo in capitalization in the word "contains" in the **Readme** file .
=> fixed a typo in Readme file

index.html
Added a card containing a picture of Dialga - the god pokemon of Time and Steel!!
=> Added Dialga!

index.html
=> added card for raichu

index.html
Added eevee,caterpie and beedrill
=> Added 3 pokemon

index.html
Added another Pokemon - Lucario. Thank you! @AM1CODES for helping me towards open source.
=> Added Lucario

index.html
Added the FIre Mouse type Cyndaquil
=> Added Cyndaquil

index.html
=> Added Charmander

index.html
for my contribution to HacktoberFest 2020
=> add Charmander

index.html
=> Add Snorlax

CONTRIBUTING.md, index.css, index.html
Aadarsh contribution to Poke-Dex
1) Added a new Pokemon (Skarmory)
2) Made a few CSS changes
=> Added Skarmory

index.html
My card looks like this : 
The size of the image is correct and i have followed the community guidelines as stipulated.
=> Added a pokemon Card Tauros

about.css, about.html, index.html
Add function to close the Navbar toggle on click.
Fix CSS of about.html page for mobile version
@AM1CODES, it won't break the code at all.. Please look into it.
=> Fix Mobile Version

index.html
I have added Ghost type Pokemon
=> ghost type pokemon added

index.html
=> added shedinja

index.html
Adding a Ho-oh a legendary mysterious pokemon that is seen by ash the first time when he started his journey
=> added hu-oh

images/added Rayquaza
=> Create added Rayquaza

index.html
Hi @AM1CODES, let me introduce Torchic in this Pokedex.
I'm adding Torchic beside his best friend Mudkip as the same starter pokemon on pokemon ruby generation.
=> Introduce Torchic

index.html
Added a card with my fav pokemon on it
=> Jigglypuff

index.html
The image was not displaying for Snorlax and I have added my favorite pokemon details which is not there in the Pokedex.
=> Added a pokemon and solved a pic loading problem for snorlax

index.html
=> Nikhil added a card

index.html
Partial Fix for #208
Removed cards from
1. https://www.github.com/alok182011
2. https://github.com/chait04
3. https://github.com/Itsaadarsh
4. https://github.com/EMTEE-001
=> Removed reduntant code

index.css, index.html
Hey :)
I have changed the background of your website.
Please have a look
=> Updated the Background of the Website

index.html
I have added a new Pokemon which is not repeated on the original index.html. Please review & check.
=> Added Zoroark

index.html
Added Aurorus to the poke dex 
and to make it count plz added hacktoberfest - accepted label to it ^^
=> Added Aurorus to the poke dex

about.html, index.html
Added Fletchinder Pokemon image and Description on main page.
Added My own info in about.html page.
Happy Hacktober !
=> Added Fletchinder pokemon

index.css, index.html
I have updated the text alignment and arrow position.
=> Updated the text alignment and down arrow position. 

index.html
=> Adds Growlithe

index.html
=> Update index.html - Darmanitan

index.html
Added details of tirtouga pokemon.
=> Added tirtouga pokemon

index.html
=> added kecleon

index.html
=> added more Pokémons

index.html
Added Pokemon Card (Vaporeon) using bootstrap template
-Choosing to add this pokemon as it is not yet on the list
=> Added Pokemon Card (Vaporeon)

index.html
=> Added Totodile

index.html
added Grimmsnarl to index.html
=> added Grimmsnarl to the index.html

index.html
I added 5 more pokémon to the list. Would love if you could mark the PR as hacktoberfest-accepted :)
=> added a few more pokémons

index.html
Added Zorua, Solosis, Reuniclus. Would appreciate it if you could mark the PR as hacktoberfest-accepted :)
=> added 3 pokemons

index.css, index.html
tested for chrome and firefox on linux
=> Page is now responsive

index.html
@AM1CODES #2 Thank you for this opportunity. I am loving learning to use open source.  Happy Hacktoberfest!
=> Added the Leafeon card to the Pokedex, aka the index.html

index.html
Togekiss's image wasn't loading, so I changed the src link.
=> Fixed Togekiss's broken image link

index.html
=> Add crabrawler

index.html
=> added espeon

index.html
=> added deoxys

index.html
I am really glad to work on this. As a pokemon fan, it brings back memories.
=> 4-pokemon update

index.html
=> Added Kingler

index.html
=> Added Krabby

index.html
Previously I uploaded Kingler card but was showing some issue. So, I have updated it with new Kingler profile. Both profiles was made by me only. Consider my PR and merge it. Thank you. @AM1CODES
=> Updated Kingler with some fixes.

index.html
Added new card details in index.html
=> added new card details

index.html
-Created new branch "101620-adam".
-Added  Wortortle, Charmeleon, and Metapod to index page.
-Used DirtyMarkup to clean up the HTML formatting and remove extra tags.
=> Created new branch "101620-adam"

index.html
Added the Pokemon Herdier to index.html
=> Added Herdier card to index.html

index.html
Added Ducklett. This is for Hacktoberfest. Please consider merging : )
=> Added Ducklet

index.html
=> update pokemon in index.html

index.html
=> added shinx

index.html
Saw that Kartana isn't on here yet so I added him :)
=> Added Kartana

index.html
I didn't find Hitmonlee's card, and he is my favourite Pokémon :)
=> Added Hitmonlee

index.css, index.html
I have made the website responsive . So kindly review it.
=> website responsive

index.html
@AM1CODES i'm reopening my PR, please review this. Thanks
=> Add Toxicroak to poke-dex

index.html
=> Add Carbink card

index.html
=> Add Dragapult

index.html
#2 
Removed extra div that was breaking the style on the lower part of the page. Also added a new pokemon that was not on the page.
=> added new pokemen and removed extra div that was breaking page style

index.html
#2 Added new Pokémon Poochyena
=> Add Poochyena

index.html
* Add Glceon
* Add a missing closing div tag before closing section
* Fix identation on index.html
=> Add Glaceon

index.html
=> felipprodrigues pokemon add

index.html
Many of the alt tags were blank. I added the Pokemon's name to any of the blank alt tags, and fixed a few that weren't the Pokemon name to help with accessibility and uniformity.
Closes #458 `Update alt attribute of img tags where empty`
=> Added Pokemon name to alt tags

index.html
The one with glasses, to be more precise.
=> Added Squirtle to the Poke-Dex

index.html
Luxray is an electric pokemon. Luxray can see through solid objects. It will instantly spot prey trying to hide behind walls, even if the walls are thick.
=> Add Luxray to PokeDex

index.html
Fire-type pokemon
- charizard, ash's 2nd favorite pokemon
- He usses charizard in difficult situation
=> Added about charizard a fire type pokemon

index.css
Added scale animation to the pokemon cards.
=> Added scale animation

index.html
=> added Wurmple pokemon

index.html
=> Fixed image rendering issues of many pokemons

ANIMATED GLOWING PROGRESS BAR/index.html, ANIMATED GLOWING PROGRESS BAR/style.css
Animated Glowing Progress Bar which can be used ti depict user progress. You can edit as per your need.
=> Animated Glowing Progress Bar

index.html
=> Added Sylveon for HaylzRandom

index.html
Hey, I have added my favorite pokemon Cresselia.
Cheers!
=> Added my favorite pokemon- Cresselia

index.html
It was fun contributing to this repo. Please merge it :)
=> Added my fav pokemon

index.html
@AM1CODES  Added Banette Card.
Pls mark hactoberfest accepted label if PR is valid. Thanks.
=> Added Banette Card

index.html
=> Revert "Added Vulpix pokemon"

index.html, pokemon.json
I am making a pull request again after editing it!
I'm sorry to have been troublesome
=> Add vulpix poke

index.css
Hey, Added the description hover effect. This will increase the evenness of the site and site will look beautiful. It wont hamper the original design of the card so not to worry.
Let's catch more pokemon
=> Updated index.css and Added Description Hover Effect

README.md, index.css, index.html
- Adding badges to the first few without
- Corrected spelling on "Ghost"
- Added alt text to all images with missing ones
=> Correct ghost spelling, add badges, and image alts

.gitignore, .idea/Poke-Dex.iml, .vscode/settings.json
also updates: .gitignore to prevent future pushes of IDE folders
=> improve repo: delete IDE specific content
